services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inh-control-predios-db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Inh_Dev_123!'
    ports:
      - '1433:1433'
    volumes:
      - inh_sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Inh_Dev_123!" -C -Q "SELECT 1" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  inh_sql_data:
